{{- if (.Values.frost.db.volume.enabled) and eq .Values.frost.db.volume.storageClassName "local" -}}
{{- $tier := "db-local-volume" -}}
{{- $fullName := include "frost-server.fullName" (merge (dict "tier" $tier) .) -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
    component: {{ $tier }}
spec:
  storageClassName: local
  capacity:
    storage: {{ .Values.frost.db.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.frost.db.volume.local.nodeMountPath }}
{{- end -}}