{{ if eq .Values.components.db.volume.storageClassName "local" }}
{{ $app := include "app" . }}
{{ $component := "db-local-volume" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  storageClassName: local
  capacity:
    storage: {{ .Values.components.db.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.components.db.volume.local.path }}
{{ end }}