{{- if (.Values.frost.db.volume.enabled) and eq .Values.frost.db.volume.storageClassName "local" -}}
{{- $app := include "app" . -}}
{{- $component := "db-local-volume" -}}
{{- $fullName := printf "%s-%s" $app $component -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  storageClassName: local
  capacity:
    storage: {{ .Values.frost.db.volume.capacity }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.frost.db.volume.local.nodeMountPath }}
{{- end -}}