{{ $tier := "db" }}
{{ $fullName := printf "%s-%s" .Chart.Name $tier }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
spec:
  selector:
    app: {{ .Chart.Name }}
    tier: {{ $tier }}
  externalIPs:
    - {{ template "externalIp" . }}
  ports:
    - name: postgresql
      port: {{ .Values.modules.db.ports.externals.postgresql }}
      targetPort: postgresql