{{- $app := include "app" . -}}
{{- $component := "db-volume-claim" -}}
{{- $fullName := printf "%s-%s" $app $component -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  storageClassName: {{ .Values.frost.db.volume.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.frost.db.volume.capacity }}
  accessModes:
    - ReadWriteOnce