{{ $app := include "app" . }}
{{ $component := "http" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      chart: {{ template "chart" . }}
      app: {{ $app }}
      component: {{ $component }}
  replicas: {{ .Values.frost.http.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "chart" . }}
        app: {{ $app }}
        component: {{ $component }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: fraunhoferiosb/frost-server-http:1.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: tomcat
              containerPort: 8080
          env:
            # Internal properties
            - name: ApiVersion
              value: {{ template "apiVersion" . }}
            - name: serviceRootUrl
              value: {{ template "serviceRootUrl" . }}

            # HTTP related properties
            - name: defaultCount
              value: {{ .Values.frost.http.defaultCount | quote }}
            - name: defaultTop
              value: {{ .Values.frost.http.defaultTop | quote }}
            - name: maxTop
              value: {{ .Values.frost.http.maxTop | quote }}
            - name: maxDataSize
              value: {{ .Values.frost.http.maxDataSize | int64 | quote }}
            - name: useAbsoluteNavigationLinks
              value: {{ .Values.frost.http.useAbsoluteNavigationLinks | quote }}

            {{ if .Values.frost.mqtt.enabled }}
            # MQTT broker related properties
            - name: bus_busImplementationClass
              value: "de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus"
            - name: bus_mqttBroker
              value: tcp://{{ $app }}-mqtt-broker:1883
            - name: bus_sendWorkerPoolSize
              value: {{ .Values.frost.mqtt.broker.sendWorkerPoolSize | quote }}
            - name: bus_sendQueueSize
              value: {{ .Values.frost.mqtt.broker.sendQueueSize | quote }}
            - name: bus_recvWorkerPoolSize
              value: {{ .Values.frost.mqtt.broker.recvWorkerPoolSize | quote }}
            - name: bus_recvQueueSize
              value: {{ .Values.frost.mqtt.broker.recvQueueSize | quote }}
            - name: bus_topicName
              value: {{ .Values.frost.mqtt.broker.topicName }}
            - name: bus_qosLevel
              value: {{ .Values.frost.mqtt.broker.qosLevel | quote }}
            - name: bus_maxInFlight
              value: {{ .Values.frost.mqtt.broker.maxInFlight | quote }}
            {{ end }}

            # Persistence related properties
            - name: persistence_persistenceManagerImplementationClass
              value: {{ .Values.frost.db.persistenceManagerImplementationClass }}
            - name: persistence_alwaysOrderbyId
              value: {{ .Values.frost.db.alwaysOrderbyId | quote }}
            - name: persistence_idGenerationMode
              value: {{ .Values.frost.db.idGenerationMode }}

            # Persistence related properties only used to set the META-INF/context.xml file
            - name: _persistence_db_username
              valueFrom:
                secretKeyRef:
                  name: {{ $app }}-secret
                  key: db.username
            - name: _persistence_db_password
              valueFrom:
                secretKeyRef:
                  name: {{ $app }}-secret
                  key: db.password
          command:
            - /bin/sh
          args:
            - -c
            - >
              mv /usr/local/tomcat/webapps/FROST-Server.war /tmp
              && rm -rf /usr/local/tomcat/webapps/*
              && unzip -d /usr/local/tomcat/webapps/ROOT /tmp/FROST-Server.war
              && sed -i 's#jdbc:postgresql://database:5432/sensorthings#jdbc:postgresql://{{ $app }}-db:5432/{{ .Values.frost.db.database }}#' /usr/local/tomcat/webapps/ROOT/META-INF/context.xml
              && sed -E -i "s#maxTotal=\"[^\"]+\"#maxTotal=\"{{ .Values.frost.db.maximumConnection }}\"#" /usr/local/tomcat/webapps/ROOT/META-INF/context.xml
              && sed -E -i "s#maxIdle=\"[^\"]+\"#maxIdle=\"{{ .Values.frost.db.maximumIdleConnection }}\"#" /usr/local/tomcat/webapps/ROOT/META-INF/context.xml
              && sed -E -i "s#username=\"[^\"]+\"#username=\"$_persistence_db_username\"#" /usr/local/tomcat/webapps/ROOT/META-INF/context.xml
              && unset _persistence_db_username
              && sed -E -i "s#password=\"[^\"]+\"#password=\"$_persistence_db_password\"#" /usr/local/tomcat/webapps/ROOT/META-INF/context.xml
              && unset _persistence_db_password
              && rm /tmp/FROST-Server.war
              && catalina.sh run