{{- $app := include "app" . -}}
{{- $component := "http" -}}
{{- $fullName := printf "%s-%s" $app $component -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      chart: {{ include "chart" . }}
      app: {{ $app }}
      component: {{ $component }}
  replicas: {{ .Values.frost.http.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ include "chart" . }}
        app: {{ $app }}
        component: {{ $component }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: fraunhoferiosb/frost-server-http:1.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: tomcat
              containerPort: 8080
          env:
            # Internal properties
            - name: ApiVersion
              value: {{ include "apiVersion" . | quote }}
            - name: serviceRootUrl
              value: {{ include "serviceRootUrl" . | quote }}

            # HTTP related properties
            - name: defaultCount
              value: "{{ .Values.frost.http.defaultCount }}"
            - name: defaultTop
              value: "{{ .Values.frost.http.defaultTop }}"
            - name: maxTop
              value: "{{ .Values.frost.http.maxTop }}"
            - name: maxDataSize
              value: "{{ .Values.frost.http.maxDataSize | int64 }}"
            - name: useAbsoluteNavigationLinks
              value: "{{ .Values.frost.http.useAbsoluteNavigationLinks }}"

            {{ if .Values.frost.mqtt.enabled -}}
            # MQTT broker related properties
            - name: bus_busImplementationClass
              value: "de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus"
            - name: bus_mqttBroker
              value: "tcp://{{ $app }}-mqtt-broker:1883"
            - name: bus_sendWorkerPoolSize
              value: "{{ .Values.frost.mqtt.broker.sendWorkerPoolSize }}"
            - name: bus_sendQueueSize
              value: "{{ .Values.frost.mqtt.broker.sendQueueSize }}"
            - name: bus_recvWorkerPoolSize
              value: "{{ .Values.frost.mqtt.broker.recvWorkerPoolSize }}"
            - name: bus_recvQueueSize
              value: "{{ .Values.frost.mqtt.broker.recvQueueSize }}"
            - name: bus_topicName
              value: "{{ .Values.frost.mqtt.broker.topicName }}"
            - name: bus_qosLevel
              value: "{{ .Values.frost.mqtt.broker.qosLevel }}"
            - name: bus_maxInFlight
              value: "{{ .Values.frost.mqtt.broker.maxInFlight }}"
            {{- end }}

            # Persistence related properties
            - name: persistence_persistenceManagerImplementationClass
              value: "{{ .Values.frost.db.persistenceManagerImplementationClass }}"
            - name: persistence_alwaysOrderbyId
              value: "{{ .Values.frost.db.alwaysOrderbyId }}"
            - name: persistence_idGenerationMode
              value: "{{ .Values.frost.db.idGenerationMode }}"
            - name: persistence_db_jndi_datasource
              value: ""
            - name: persistence_db_driver
              value: "org.postgresql.Driver"
            - name: persistence_db_url
              value: "jdbc:postgresql://{{ $app }}-db:{{ .Values.frost.db.ports.postgresql.servicePort }}/{{ .Values.frost.db.database }}"
            - name: persistence_db_username
              valueFrom:
                secretKeyRef:
                  name: {{ $app }}-secret
                  key: db.username
            - name: persistence_db_password
              valueFrom:
                secretKeyRef:
                  name: {{ $app }}-secret
                  key: db.password
            - name: persistence_db_conn_max
              value: "{{ .Values.frost.db.maximumConnection }}"
            - name: persistence_db_conn_idle_max
              value: "{{ .Values.frost.db.maximumIdleConnection }}"
            - name: persistence_db_conn_idle_min
              value: "{{ .Values.frost.db.maximumIdleConnection }}"

          # Execute some operations before to launch the FROST-Server HTTP's WAR:
          #   1. Remove all existing Tomcat webapps
          #   2. Set the access to the FROST-Server HTTP API at the Tomcat's root
          #   3. Clean environment (remove the unnecessary WAR)
          command:
            - /bin/sh
          args:
            - -c
            - >
              mv /usr/local/tomcat/webapps/FROST-Server.war /tmp
              && rm -rf /usr/local/tomcat/webapps/*
              && unzip -d /usr/local/tomcat/webapps/ROOT /tmp/FROST-Server.war
              && rm /tmp/FROST-Server.war
              && catalina.sh run