{{ $tier := "http" }}
{{ $fullName := printf "%s-%s" .Chart.Name $tier }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: {{ $tier }}
  replicas: {{ .Values.modules.http.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: {{ $tier }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: fraunhoferiosb/frost-server-http:1.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.modules.http.ports.internals.http }}
          env:
            # Internal properties
            - name: ApiVersion
              value: {{ template "apiVersion" . }}
            - name: serviceRootUrl
              value: {{ template "serviceRootUrl" . }}

            # HTTP related properties
            - name: defaultCount
              value: {{ .Values.modules.http.defaultCount | quote }}
            - name: defaultTop
              value: {{ .Values.modules.http.defaultTop | quote }}
            - name: maxTop
              value: {{ .Values.modules.http.maxTop | quote }}
            - name: maxDataSize
              value: {{ .Values.modules.http.maxDataSize | int64 | quote }}
            - name: useAbsoluteNavigationLinks
              value: {{ .Values.modules.http.useAbsoluteNavigationLinks | quote }}

            {{ if .Values.modules.mqtt.enabled }}
            # MQTT broker related properties
            - name: bus_busImplementationClass
              value: "de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus"
            - name: bus_mqttBroker
              value: tcp://{{ .Chart.Name }}-mqtt-broker:1883
            - name: bus_sendWorkerPoolSize
              value: {{ .Values.modules.mqtt.broker.sendWorkerPoolSize | quote }}
            - name: bus_sendQueueSize
              value: {{ .Values.modules.mqtt.broker.sendQueueSize | quote }}
            - name: bus_recvWorkerPoolSize
              value: {{ .Values.modules.mqtt.broker.recvWorkerPoolSize | quote }}
            - name: bus_recvQueueSize
              value: {{ .Values.modules.mqtt.broker.recvQueueSize | quote }}
            - name: bus_topicName
              value: {{ .Values.modules.mqtt.broker.topicName }}
            - name: bus_qosLevel
              value: {{ .Values.modules.mqtt.broker.qosLevel | quote }}
            - name: bus_maxInFlight
              value: {{ .Values.modules.mqtt.broker.maxInFlight | quote }}
            {{ end }}

            # Persistence related properties
            - name: persistence_persistenceManagerImplementationClass
              value: {{ .Values.modules.db.persistenceManagerImplementationClass }}
            - name: persistence_alwaysOrderbyId
              value: {{ .Values.modules.db.alwaysOrderbyId | quote }}
            - name: persistence_idGenerationMode
              value: {{ .Values.modules.db.idGenerationMode }}

            # Persistence related properties only used to set the META-INF/context.xml file
            - name: _persistence_db_username
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.username
            - name: _persistence_db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.password
          command:
            - /bin/sh
          args:
            - -c
            - >
              unzip -d /usr/local/tomcat/webapps/FROST-Server /usr/local/tomcat/webapps/FROST-Server.war
              && sed -i 's#jdbc:postgresql://database:5432/sensorthings#jdbc:postgresql://{{ .Chart.Name }}-db:5432/{{ .Values.modules.db.database }}#' /usr/local/tomcat/webapps/FROST-Server/META-INF/context.xml
              && sed -E -i "s#maxTotal=\"[^\"]+\"#maxTotal=\"{{ .Values.modules.db.maximumConnection }}\"#" /usr/local/tomcat/webapps/FROST-Server/META-INF/context.xml
              && sed -E -i "s#maxIdle=\"[^\"]+\"#maxIdle=\"{{ .Values.modules.db.maximumIdleConnection }}\"#" /usr/local/tomcat/webapps/FROST-Server/META-INF/context.xml
              && sed -E -i "s#username=\"[^\"]+\"#username=\"$_persistence_db_username\"#" /usr/local/tomcat/webapps/FROST-Server/META-INF/context.xml
              && unset _persistence_db_username
              && sed -E -i "s#password=\"[^\"]+\"#password=\"$_persistence_db_password\"#" /usr/local/tomcat/webapps/FROST-Server/META-INF/context.xml
              && unset _persistence_db_password
              && rm /usr/local/tomcat/webapps/FROST-Server.war
              && catalina.sh run