{{ $app := include "app" . }}
{{ $component := "http" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
  externalIPs:
    - {{ template "externalIp" . }}
  ports:
    - name: http
      port: {{ .Values.frost.http.ports.http }}
      targetPort: http