{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "frost-server.fullName" . }}
  labels:
    heritage: {{ .Release.Service }}
    chart: {{ include "frost-server.chart" . }}
    app: {{ include "frost-server.name" . }}
spec:
  rules:
  - host: {{ .Values.cluster.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "frost-server.fullName" (merge (dict "tier" "http") .) }}
          servicePort: {{ .Values.frost.http.ports.http.servicePort }}
{{- end -}}