{{ if .Values.frost.mqtt.enabled }}
{{ $app := include "app" . }}
{{ $component := "mqtt" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    matchLabels:
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
      chart: {{ template "chart" . }}
      app: {{ $app }}
      component: {{ $component }}
  replicas: {{ .Values.frost.mqtt.replicas }}
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
        chart: {{ template "chart" . }}
        app: {{ $app }}
        component: {{ $component }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: fraunhoferiosb/frost-server-mqtt:1.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: 1883
            - name: websocket
              containerPort: 9876
          env:
            # Internal properties
            - name: ApiVersion
              value: {{ template "apiVersion" . }}
            - name: serviceRootUrl
              value: {{ template "serviceRootUrl" . }}

            # HTTP related properties
            - name: defaultCount
              value: {{ .Values.frost.http.defaultCount | quote }}
            - name: defaultTop
              value: {{ .Values.frost.http.defaultTop | quote }}
            - name: maxTop
              value: {{ .Values.frost.http.maxTop | quote }}
            - name: maxDataSize
              value: {{ .Values.frost.http.maxDataSize | int64 | quote }}
            - name: useAbsoluteNavigationLinks
              value: {{ .Values.frost.http.useAbsoluteNavigationLinks | quote }}

            # MQTT related properties
            - name: mqtt_mqttServerImplementationClass
              value: "de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer"
            - name: mqtt_Enabled
              value: "true"
            - name: mqtt_Port
              value: "1883"
            - name: mqtt_Host
              value: "0.0.0.0"
            - name: mqtt_internalHost
              value: "localhost"
            - name: mqtt_WebsocketPort
              value: "9876"
            - name: mqtt_QoS
              value: {{ .Values.frost.mqtt.qos | quote }}
            - name: mqtt_SubscribeMessageQueueSize
              value: {{ .Values.frost.mqtt.subscribeMessageQueueSize | quote }}
            - name: mqtt_SubscribeThreadPoolSize
              value: {{ .Values.frost.mqtt.subscribeThreadPoolSize | quote }}
            - name: mqtt_CreateMessageQueueSize
              value: {{ .Values.frost.mqtt.createMessageQueueSize | quote }}
            - name: mqtt_CreateThreadPoolSize
              value: {{ .Values.frost.mqtt.createThreadPoolSize | quote }}
            - name: mqtt_maxInFlight
              value: {{ .Values.frost.mqtt.maxInFlight | quote }}
            - name: mqtt_WaitForEnter
              value: {{ .Values.frost.mqtt.waitForEnter | quote }}

            # MQTT broker related properties
            - name: bus_busImplementationClass
              value: "de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus"
            - name: bus_mqttBroker
              value: tcp://{{ .Chart.Name }}-mqtt-broker:1883
            - name: bus_sendWorkerPoolSize
              value: {{ .Values.frost.mqtt.broker.sendWorkerPoolSize | quote }}
            - name: bus_sendQueueSize
              value: {{ .Values.frost.mqtt.broker.sendQueueSize | quote }}
            - name: bus_recvWorkerPoolSize
              value: {{ .Values.frost.mqtt.broker.recvWorkerPoolSize | quote }}
            - name: bus_recvQueueSize
              value: {{ .Values.frost.mqtt.broker.recvQueueSize | quote }}
            - name: bus_topicName
              value: {{ .Values.frost.mqtt.broker.topicName }}
            - name: bus_qosLevel
              value: {{ .Values.frost.mqtt.broker.qosLevel | quote }}
            - name: bus_maxInFlight
              value: {{ .Values.frost.mqtt.broker.maxInFlight | quote }}

            # Persistence related properties
            - name: persistence_db_driver
              value: "org.postgresql.Driver"
            - name: persistence_persistenceManagerImplementationClass
              value: {{ .Values.frost.db.persistenceManagerImplementationClass }}
            - name: persistence_alwaysOrderbyId
              value: {{ .Values.frost.db.alwaysOrderbyId | quote }}
            - name: persistence_idGenerationMode
              value: {{ .Values.frost.db.idGenerationMode }}
            - name: persistence_db_url
              value: jdbc:postgresql://{{ .Chart.Name }}-db:5432/{{ .Values.frost.db.database }}
            - name: persistence_db_conn_max
              value: {{ .Values.frost.db.maximumConnection | quote }}
            - name: persistence_db_conn_idle_max
              value: {{ .Values.frost.db.maximumIdleConnection | quote }}
            - name: persistence_db_conn_idle_min
              value: {{ .Values.frost.db.minimumIdleConnection | quote }}
            - name: persistence_db_username
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.username
            - name: persistence_db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.password
{{ end }}