{{ if .Values.frost.mqtt.enabled }}
{{ $app := include "app" . }}
{{ $component := "mqtt-broker" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
  ports:
    - name: mqtt
      port: {{ .Values.frost.mqtt.broker.ports.internals.mqtt }}
      targetPort: mqtt
{{ end }}