{{ if .Values.modules.mqtt.enabled }}
{{ $tier := "mqtt" }}
{{ $fullName := printf "%s-%s" .Chart.Name $tier }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      tier: {{ $tier }}
  replicas: {{ .Values.modules.mqtt.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        tier: {{ $tier }}
    spec:
      containers:
        - name: {{ $fullName }}
          image: fraunhoferiosb/frost-server-mqtt:1.7
          imagePullPolicy: IfNotPresent
          ports:
            - name: mqtt
              containerPort: {{ .Values.modules.mqtt.ports.internals.mqtt }}
            - name: websocket
              containerPort: {{ .Values.modules.mqtt.ports.internals.websocket }}
          env:
            # Internal properties
            - name: ApiVersion
              value: {{ template "apiVersion" . }}
            - name: serviceRootUrl
              value: {{ template "serviceRootUrl" . }}

            # HTTP related properties
            - name: defaultCount
              value: {{ .Values.modules.http.defaultCount | quote }}
            - name: defaultTop
              value: {{ .Values.modules.http.defaultTop | quote }}
            - name: maxTop
              value: {{ .Values.modules.http.maxTop | quote }}
            - name: maxDataSize
              value: {{ .Values.modules.http.maxDataSize | int64 | quote }}
            - name: useAbsoluteNavigationLinks
              value: {{ .Values.modules.http.useAbsoluteNavigationLinks | quote }}

            # MQTT related properties
            - name: mqtt_mqttServerImplementationClass
              value: "de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer"
            - name: mqtt_Enabled
              value: "true"
            - name: mqtt_Port
              value: "1883"
            - name: mqtt_Host
              value: "0.0.0.0"
            - name: mqtt_internalHost
              value: "localhost"
            - name: mqtt_WebsocketPort
              value: "9876"
            - name: mqtt_QoS
              value: {{ .Values.modules.mqtt.qos | quote }}
            - name: mqtt_SubscribeMessageQueueSize
              value: {{ .Values.modules.mqtt.subscribeMessageQueueSize | quote }}
            - name: mqtt_SubscribeThreadPoolSize
              value: {{ .Values.modules.mqtt.subscribeThreadPoolSize | quote }}
            - name: mqtt_CreateMessageQueueSize
              value: {{ .Values.modules.mqtt.createMessageQueueSize | quote }}
            - name: mqtt_CreateThreadPoolSize
              value: {{ .Values.modules.mqtt.createThreadPoolSize | quote }}
            - name: mqtt_maxInFlight
              value: {{ .Values.modules.mqtt.maxInFlight | quote }}
            - name: mqtt_WaitForEnter
              value: {{ .Values.modules.mqtt.waitForEnter | quote }}

            # MQTT broker related properties
            - name: bus_busImplementationClass
              value: "de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus"
            - name: bus_mqttBroker
              value: tcp://{{ .Chart.Name }}-mqtt-broker:1883
            - name: bus_sendWorkerPoolSize
              value: {{ .Values.modules.mqtt.broker.sendWorkerPoolSize | quote }}
            - name: bus_sendQueueSize
              value: {{ .Values.modules.mqtt.broker.sendQueueSize | quote }}
            - name: bus_recvWorkerPoolSize
              value: {{ .Values.modules.mqtt.broker.recvWorkerPoolSize | quote }}
            - name: bus_recvQueueSize
              value: {{ .Values.modules.mqtt.broker.recvQueueSize | quote }}
            - name: bus_topicName
              value: {{ .Values.modules.mqtt.broker.topicName }}
            - name: bus_qosLevel
              value: {{ .Values.modules.mqtt.broker.qosLevel | quote }}
            - name: bus_maxInFlight
              value: {{ .Values.modules.mqtt.broker.maxInFlight | quote }}

            # Persistence related properties
            - name: persistence_db_driver
              value: "org.postgresql.Driver"
            - name: persistence_persistenceManagerImplementationClass
              value: {{ .Values.modules.db.persistenceManagerImplementationClass }}
            - name: persistence_alwaysOrderbyId
              value: {{ .Values.modules.db.alwaysOrderbyId | quote }}
            - name: persistence_idGenerationMode
              value: {{ .Values.modules.db.idGenerationMode }}
            - name: persistence_db_url
              value: jdbc:postgresql://{{ .Chart.Name }}-db:5432/{{ .Values.modules.db.database }}
            - name: persistence_db_conn_max
              value: {{ .Values.modules.db.maximumConnection | quote }}
            - name: persistence_db_conn_idle_max
              value: {{ .Values.modules.db.maximumIdleConnection | quote }}
            - name: persistence_db_conn_idle_min
              value: {{ .Values.modules.db.minimumIdleConnection | quote }}
            - name: persistence_db_username
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.username
            - name: persistence_db_password
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: db.password
{{ end }}