{{ if .Values.frost.mqtt.enabled }}
{{ $app := include "app" . }}
{{ $component := "mqtt" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
spec:
  selector:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
  type: NodePort
  ports:
    - name: mqtt
      port: {{ .Values.frost.mqtt.ports.mqtt.servicePort }}
      nodePort: {{ .Values.frost.mqtt.ports.mqtt.nodePort }}
      targetPort: mqtt
    - name: websocket
      port: {{ .Values.frost.mqtt.ports.websocket.servicePort }}
      nodePort: {{ .Values.frost.mqtt.ports.websocket.nodePort }}
      targetPort: websocket
{{ end }}