{{- $app := include "app" . -}}
{{- $component := "secret" -}}
{{- $fullName := printf "%s-%s" $app $component -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ include "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
data:
  db.username: {{ .Values.frost.db.username }}
  db.password: {{ .Values.frost.db.password }}