{{ $app := include "app" . }}
{{ $component := "secret" }}
{{ $fullName := printf "%s-%s" $app $component }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ template "chart" . }}
    app: {{ $app }}
    component: {{ $component }}
data:
  db.username: {{ .Values.components.db.username }}
  db.password: {{ .Values.components.db.password }}