# The optional value to override common base name for any FROST-Server Kubernetes resources
nameOverride:

cluster:
  host: frost-server

ingress:
  enabled: false

persistence:
  enabled: false
  storageClassName: local
  capacity: 10Gi
  local:
    nodeMountPath: /mnt/frost-server-db

frost:
  ##########################################
  # FROST-Server HTTP module configuration #
  ##########################################
  http:
    # FROST-Server HTTP deployment settings
    replicas: 1
    ports:
      http:
        nodePort: 30080
        servicePort: 80

    # FROST-Server HTTP business settings
    defaultCount: false
    defaultTop: 100
    maxTop: 1000
    maxDataSize: 25000000
    useAbsoluteNavigationLinks: true

    # FROST-Server HTTP's FROST-Server Database settings
    db:
      alwaysOrderbyId: false
      maximumConnection: 10
      maximumIdleConnection: 10
      minimumIdleConnection: 10

  ##############################################
  # FROST-Server Database module configuration #
  ##############################################
  db:
    # FROST-Server Database deployment settings
    ports:
      postgresql:
        servicePort: 5432

    # Common FROST-Server Database properties, shared by any other FROST-Server modules
    persistenceManagerImplementationClass: "de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong"
    idGenerationMode: "ServerGeneratedOnly"
    database: sensorthings
    username: c2Vuc29ydGhpbmdz
    password: bm93eW91Y2FuY2hhbmdlaXQ=

  ##########################################
  # FROST-Server MQTT module configuration #
  ##########################################
  mqtt:
    # FROST-Server MQTT deployment settings
    enabled: true
    replicas: 1
    ports:
      mqtt:
        nodePort: 30883
        servicePort: 1883
      websocket:
        nodePort: 30876
        servicePort: 9876

    # FROST-Server MQTT business settings
    qos: 2
    subscribeMessageQueueSize: 100
    subscribeThreadPoolSize: 10
    createMessageQueueSize: 100
    createThreadPoolSize: 10
    maxInFlight: 50
    waitForEnter: false

    # FROST-Server MQTT's FROST-Server Database settings
    db:
      alwaysOrderbyId: false
      maximumConnection: 10
      maximumIdleConnection: 10
      minimumIdleConnection: 10

    broker:
      # Module deployment settings
      ports:
        mqtt:
          servicePort: 1883

      # Module business settings
      sendWorkerPoolSize: 10
      sendQueueSize: 100
      recvWorkerPoolSize: 10
      recvQueueSize: 100
      topicName: "FROST-Bus"
      qosLevel: 2
      maxInFlight: 50