app: frost-server
externalIp: # Put here the IP of the target Kubernetes cluster (required value)

frost:
  http:
    # Module deployment settings
    replicas: 1
    ports:
      http: 80

    # Module business settings
    defaultCount: false
    defaultTop: 100
    maxTop: 1000
    maxDataSize: 25000000
    useAbsoluteNavigationLinks: true

  db:
    # Module deployment settings
    ports:
      postgresql: 5432
    volume:
      storageClassName: local
      capacity: 10Gi
      local:
        path: /mnt/frost-server-db

    # Module business settings
    persistenceManagerImplementationClass: "de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong"
    idGenerationMode: "ServerGeneratedOnly"
    alwaysOrderbyId: false
    maximumConnection: 10
    maximumIdleConnection: 10
    minimumIdleConnection: 10
    database: sensorthings
    username: c2Vuc29ydGhpbmdz
    password: bm93eW91Y2FuY2hhbmdlaXQ=

  mqtt:
    # Module deployment settings
    enabled: true
    replicas: 1
    ports:
      mqtt: 1883
      websocket: 9876

    # Module business settings
    qos: 2
    subscribeMessageQueueSize: 100
    subscribeThreadPoolSize: 10
    createMessageQueueSize: 100
    createThreadPoolSize: 10
    maxInFlight: 50
    waitForEnter: false

    broker:
      # Module deployment settings
      ports:
        mqtt: 1883

      # Module business settings
      sendWorkerPoolSize: 10
      sendQueueSize: 100
      recvWorkerPoolSize: 10
      recvQueueSize: 100
      topicName: "FROST-Bus"
      qosLevel: 2
      maxInFlight: 50