apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .app.components.db.volumeClaims.local.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .app.components.db.volumeClaims.local.storageSizeRequest }}